title: It all started with a map........ 
description:
author: Jonah Adkins
github: https://github.com/jonahadkins
about: Cartography, OpenStreetMap, Open Data, Music, Disney, Sports Cards, Pro-Wrestling, and Ink.
disqus_shortname:
google_analytics:
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/jonahadkins"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jonahadkins"
    - icon: fa-github
      link: "https://github.com/jonahadkins"
    - icon: fa-envelope
      link: "mailto:jonahadkins@gmail.com"

share:
  twitter_username: jonahadkins
  fb_appid:

urls:
    - text: Resume
      url: /resume_for_jonah_adkins.pdf
    - text: About
      url: /about/
    - text: Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://jonahadkins.com/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
